import type { TacticInput } from "./schemas";

export const SEED_TACTICS: TacticInput[] = [
  {
    id: "seed-1",
    tacticName: "Primetime TV – Q1 Flight",
    geoName: "US National",
    audienceName: "Adults 25-54",
    audienceSize: 125_000_000,
    channel: "TV",
    cost: 5_000_000,
    cpm: 25,
    reachPercent: undefined,
    frequency: undefined,
    grps: undefined,
    grossImpressions: undefined,
  },
  {
    id: "seed-2",
    tacticName: "Social Video – Meta + TikTok",
    geoName: "US National",
    audienceName: "Adults 25-54",
    audienceSize: 125_000_000,
    channel: "Social",
    grossImpressions: 80_000_000,
    cost: undefined,
    cpm: undefined,
    reachPercent: undefined,
    frequency: undefined,
    grps: undefined,
  },
  {
    id: "seed-3",
    tacticName: "Programmatic Display",
    geoName: "US National",
    audienceName: "Adults 25-54",
    audienceSize: 125_000_000,
    channel: "Digital",
    reachPercent: 30,
    frequency: 4,
    cost: undefined,
    cpm: undefined,
    grps: undefined,
    grossImpressions: undefined,
  },
];
